<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hms-update3" name="com.hms.APITestingUsingUnirest.SmokeTest" tests="36" failures="1" timestamp="17 Jul 2017 07:36:51 GMT" time="118.543" errors="5">
  <testcase name="UC_FD_24_TC_1_getinvoices" time="2.920" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_4_TC_1_commitedbooking" time="4.829" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_84_TC_1_sendbookingemail" time="4.255" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_30_TC_1_getgroupcancellationcharge" time="3.085" classname="com.hms.APITestingUsingUnirest.SmokeTest">
    <failure type="org.json.JSONException" message="JSONArray[-2] not found.">
      <![CDATA[org.json.JSONException: JSONArray[-2] not found.
	at org.json.JSONArray.get(JSONArray.java:194)
	at org.json.JSONArray.getJSONObject(JSONArray.java:292)
	at com.hms.APITestingUsingUnirest.Getbookings.extractinggroupmainid(Getbookings.java:202)
	at com.hms.APITestingUsingUnirest.Editbooking.Editbookingcall(Editbooking.java:128)
	at com.hms.APITestingUsingUnirest.Getgroupcancelcharge.Getgroupcancelchargecall(Getgroupcancelcharge.java:68)
	at com.hms.APITestingUsingUnirest.SmokeTest.UC_FD_30_TC_1_getgroupcancellationcharge(SmokeTest.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- UC_FD_30_TC_1_getgroupcancellationcharge -->
  <testcase name="UC_FD_14_TC_1_getdnrs" time="1.247" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_56_TC_1_checknightauditstatus" time="1.153" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_50_TC_1_adddnrs" time="3.068" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_3_TC_1_editbooking" time="3.837" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_59_TC_1_earlycheckout" time="3.190" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_52_TC_1_editdnrs" time="2.469" classname="com.hms.APITestingUsingUnirest.SmokeTest">
    <error type="java.lang.AssertionError" message="expected [success] but found [Not possible to edit DNR]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [Not possible to edit DNR]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hms.APITestingUsingUnirest.SmokeTest.UC_FD_52_TC_1_editdnrs(SmokeTest.java:364)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- UC_FD_52_TC_1_editdnrs -->
  <testcase name="UC_FD_21_TC_1_getbooking" time="3.231" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_17_TC_1_getcheckins" time="4.268" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_31_TC_1_getdepositamount" time="2.888" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_9_TC_1_getroomtypestochange" time="1.175" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_16_TC_1_gethoteldata" time="1.751" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_26_TC_1_getearlycheckincharge" time="4.305" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_58_TC_1_deleteproformainvoice" time="2.814" classname="com.hms.APITestingUsingUnirest.SmokeTest">
    <error type="java.lang.AssertionError" message="expected [success] but found [This Reservation is Already Opened by harlin mirza(dia0077)]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [This Reservation is Already Opened by harlin mirza(dia0077)]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hms.APITestingUsingUnirest.SmokeTest.UC_FD_58_TC_1_deleteproformainvoice(SmokeTest.java:418)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- UC_FD_58_TC_1_deleteproformainvoice -->
  <testcase name="UC_FD_15_TC_1_gethousestatus" time="1.428" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_20_TC_1_getbookingsearch" time="2.056" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_55_TC_1_changepayterm" time="3.398" classname="com.hms.APITestingUsingUnirest.SmokeTest">
    <error type="java.lang.AssertionError" message="expected [success] but found [This Reservation is Already Opened by harlin mirza(dia0077)]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [This Reservation is Already Opened by harlin mirza(dia0077)]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hms.APITestingUsingUnirest.SmokeTest.UC_FD_55_TC_1_changepayterm(SmokeTest.java:391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- UC_FD_55_TC_1_changepayterm -->
  <testcase name="UC_FD_25_TC_1_getinvoice" time="1.480" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_27_TC_1_getearlycheckoutcharge" time="2.884" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_57_TC_1_consolidateaccount" time="2.815" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_37_TC_1_movebooking" time="4.078" classname="com.hms.APITestingUsingUnirest.SmokeTest">
    <error type="java.lang.AssertionError" message="expected [success] but found [move not possible, checkin booking required roomId]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [move not possible, checkin booking required roomId]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hms.APITestingUsingUnirest.SmokeTest.UC_FD_37_TC_1_movebooking(SmokeTest.java:325)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- UC_FD_37_TC_1_movebooking -->
  <testcase name="UC_FD_22_TC_1_getgroup" time="3.944" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_53_TC_1_keepalive" time="1.372" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_29_TC_1_getratestochange" time="9.251" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_13_TC_1_getusers" time="1.222" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_18_TC_1_getcheckouts" time="1.440" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_70_TC_1_guestlookup" time="1.395" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_19_TC_1_getbookings" time="1.922" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_51_TC_1_deletednrs" time="2.468" classname="com.hms.APITestingUsingUnirest.SmokeTest">
    <error type="java.lang.AssertionError" message="expected [success] but found [DNR delete not possible as DNR(fXNo4hC6) is before Night Audit Date.]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [DNR delete not possible as DNR(fXNo4hC6) is before Night Audit Date.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hms.APITestingUsingUnirest.SmokeTest.UC_FD_51_TC_1_deletednrs(SmokeTest.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- UC_FD_51_TC_1_deletednrs -->
  <testcase name="UC_FD_34_TC_1_unassignroom" time="9.072" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_23_TC_1_getaccountstatements" time="3.422" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_5_TC_1_closeeditbooking" time="4.571" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
  <testcase name="UC_FD_54_TC_1_addoccupancies" time="9.840" classname="com.hms.APITestingUsingUnirest.SmokeTest"/>
</testsuite> <!-- com.hms.APITestingUsingUnirest.SmokeTest -->
